name: Commit And Run Tests

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Run script to update readme
        run: python update-readme.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: update-readme
          PULL_REQUEST_TITLE: "[CRON] Update Readme"
          PULL_REQUEST_ASSIGNEES: juan-fernandez
          PULL_REQUEST_REVIEWERS: juan-fernandez
          COMMIT_MESSAGE: Update readme
          COMMIT_AUTHOR_EMAIL: juan@undefinedlabs.com
          COMMIT_AUTHOR_NAME: Juan Fernandez
          PULL_REQUEST_BODY: |
            Automatic PR to update the readme of the repository.
